config/routes.rb
Rails.application.routes.draw do
  resources :subjects do
    resources :posts
  end

  get 'welcome/index'

  post '/login', to: 'sessions#create'

  get '/login', to: 'sessions#new', as: 'log_in'

  delete '/logout', to: 'sessions#destroy', as: 'log_out'

  resources :users do
    resources :reviews
    resources :posts
  end

  root 'welcome#index'

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  validates :category, :presence => true
  validates :name, :presence => true
  validates :year, :presence => true
  has_many :posts, class_name: 'Post', dependent: :destroy
  has_many :reviews, class_name: 'Review', dependent: :destroy
  attr_readonly :category

  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new( user_params )

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        current_user
        format.html { redirect_to subjects_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: subjects_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    reset_session
    redirect_to root_path, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :category, :name, :year, :bio, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.radio_button(:year, "Freshman") %>
    <%= f.label(:year, "Freshman") %>
    <%= f.radio_button(:year, "Sophomore") %>
    <%= f.label(:year, "Sophomore") %>
    <%= f.radio_button(:year, "Junior") %>
    <%= f.label(:year, "Junior") %>
    <%= f.radio_button(:year, "Senior") %>
    <%= f.label(:year, "Senior") %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.radio_button(:category, "Tutor") %>
    <%= f.label(:category, "Tutor") %>
    <%= f.radio_button(:category, "Tutee") %>
    <%= f.label(:category, "Tutee") %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    Upload a profile picture! 
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Category</th>
      <th>Name</th>
      <th>Year</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.category %></td>
        <td><%= user.name %></td>
        <td><%= user.year %></td>
        <td><%= user.bio %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class="container">
	<div class="row">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<h1>Sign up for your free account!</h1>
			<%= render 'form' %>
			<%= link_to 'Back', root_path %>
		</div>
		<div class="col-lg-3"></div>
	</div>
</div>

app/views/users/show.html.erb
<% if logged_in? %>
  Hey <%= link_to current_user.name, current_user %>!
<%= link_to 'Logout', log_out_path, :method => :delete %>
<% else %>
<%= link_to 'Login', log_in_path %>
<%= link_to 'Signup', new_user_path %>
<% end %>
<h1>
  <%= @user.name + "'s Homepage!" %>
</h1>

<p>
  <strong>Category:</strong>
  <%= @user.category %>
</p>

<p>
  <strong>Year:</strong>
  <%= @user.year %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<%= image_tag @user.avatar.url(:square) %>


<table>
  <thead>
    <tr>
      <% if @user.category == "Tutor" %>
      <th>Rating</th>
      <th>Review</th>
      <th>Author</th>
      <th>Created At</th>
      <% end %>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.body %></td>
        <td><%= review.author %></td>
        <td><%= review.created_at %></td>
        <% if logged_in? && review.author == current_user.name  %>
        <td><%= link_to 'Edit Review', edit_user_review_path(@user, review) %></td>
        <td><%= link_to 'Delete Review', user_review_path(@user, review), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', subjects_path %>
<% if logged_in?  %>
<% if @user != current_user %>
<% if @user.category == "Tutor" %>
<%= link_to 'Leave a Review', new_user_review_path(@user) %>
<% end %>
<% else %>
<%= link_to 'Edit', edit_user_path(@user) %>
<td><%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
<% end %>