config/routes.rb
Rails.application.routes.draw do
  resources :subjects do
    resources :posts
  end

  get 'welcome/index'

  post '/login', to: 'sessions#create'

  get '/login', to: 'sessions#new', as: 'log_in'

  delete '/logout', to: 'sessions#destroy', as: 'log_out'

  resources :users do
    resources :reviews
    resources :posts
  end

  root 'welcome#index'

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  	has_many :posts, class_name: 'Post', dependent: :destroy
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
  <header>
    <%= link_to 'Back', root_path %>
    <% if logged_in? %>
      Hey <%= link_to current_user.name, current_user %>!
      <%= link_to 'Logout', log_out_path, :method => :delete %>
    <% else %>
      <%= link_to 'Login', log_in_path %>
      <%= link_to 'Signup', new_user_path %>
    <% end %>
  </header>

<div id="subjects-background">
    <h1>Subjects</h1>
    <ul>
        <% @subjects.each do |subject| %>
            <li><%= link_to subject.name, subject %></li>
        <% end %>
    </ul>
</div>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<header>
  <%= link_to 'Back', subjects_path %>
  <% if logged_in? %>
    Hey <%= link_to current_user.name, current_user %>!
    <%= link_to 'Logout', log_out_path, :method => :delete %>
  <% else %>
    <%= link_to 'Login', log_in_path %>
    <%= link_to 'Signup', new_user_path %>
  <% end %>
</header> 

<div class="container">
  <h1 class="show"><%= @subject.name %></h1>

  <p>See if any of the following offers or requests match what you need. If not, make a 
  <% if logged_in? %>
    <%= link_to 'new post', new_subject_post_path(@subject) %>
  <% else %>
    new post
  <% end %>

    if you are logged in :-)</p>

  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th class="text-center col-lg-6 col-md-4 col-sm-4 col-xs-4">Tutoring Offers</th>
        <th class="text-center col-lg-3 col-md-4 col-sm-4 col-xs-4">Author</th>
        <th class="text-center col-lg-3 col-md-4 col-sm-4 col-xs-4">Created At</th>
      </tr>
    </thead>

    <tbody>
      <% @subject.posts.each do |post| %>
        <tr>
          <% if post.user.category == 'Tutor'%>
            <td><%= link_to post.title, subject_post_path(@subject, post) %></td>
            <td><%= link_to post.user.name, post.user %></td>
            <td><%= post.created_at.localtime.to_formatted_s(:long_ordinal)%>
            <% if logged_in? && post.user == current_user %>
              <%= link_to 'Edit', edit_subject_post_path(@subject, post) %>
              <%= link_to 'Delete', subject_post_path(@subject, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th class="text-center col-lg-6 col-md-4 col-sm-4 col-xs-4">Tutoring Requests</th>
        <th class="text-center col-lg-3 col-md-4 col-sm-4 col-xs-4">Author</th>
        <th class="text-center col-lg-3 col-md-4 col-sm-4 col-xs-4">Created At</th>
      </tr>
    </thead>

    <tbody>
      <% @subject.posts.each do |post| %>
        <tr>
          <% if post.user.category == 'Tutee'%>
            <td><%= link_to post.title, subject_post_path(@subject, post) %></td>
            <td><%= link_to post.user.name, post.user %></td>
            <td><%= post.created_at.localtime.to_formatted_s(:long_ordinal) %>
            <% if logged_in? && post.user == current_user %>
              <%= link_to 'Edit', edit_subject_post_path(@subject, post) %>
              <%= link_to 'Delete', subject_post_path(@subject, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>