config/routes.rb
Rails.application.routes.draw do
  resources :subjects do
    resources :posts
  end

  get 'welcome/index'

  post '/login', to: 'sessions#create'

  get '/login', to: 'sessions#new', as: 'log_in'

  delete '/logout', to: 'sessions#destroy', as: 'log_out'

  resources :users do
    resources :reviews
    resources :posts
  end

  root 'welcome#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    @review.user = User.find(params[:user_id])
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user = User.find(params[:user_id])
    @review.author = current_user.name

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review.user, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review.user, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @review.user, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :body, :author)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@review.user, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Rating
    <%= f.radio_button(:rating, "1") %>
    <%= f.label(:rating, "1") %>
    <%= f.radio_button(:rating, "2") %>
    <%= f.label(:rating, "2") %>
    <%= f.radio_button(:rating, "3") %>
    <%= f.label(:rating, "3") %>
    <%= f.radio_button(:rating, "4") %>
    <%= f.label(:rating, "4") %>
    <%= f.radio_button(:rating, "5") %>
    <%= f.label(:rating, "5") %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Body</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.body %></td>
        <td><%= review.author %></td>
        <td><%= link_to 'Show', review.user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', user_reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @review.author %>
</p>

<%= link_to 'Edit', edit_user_review_path(@review, @review.user) %> |
<%= link_to 'Back', @review.user %>